# data path
dataset: nuPlanMini
cache_dir: /lustre/fsw/portfolios/nvr/users/wenhaod/data/.unified_data_cache
data_dirs: 
    nuplan_mini: /lustre/fsw/portfolios/nvr/users/wenhaod/data/nuplan/dataset

# data loader
num_workers: 64
batch_size: 64
max_agent_num: 20
desired_dt: 0.5
history_sec: 5.0
future_sec: 4.0
max_number_lane: 200
num_point_per_lane: 1000
radius: 200
traj_attr: 6
map_attr: 3
num_agent_types: 5

# occupancy graph
grid_interval: 5.0
dt: 0.1
horizon: 30 